### ISSUE TITLE
Current merge-all branch installs but test suite fails

### ISSUE THREAD

**Issue by level323** [attic/merge#1]
Hi there, 

First of all, my sincere apologies in advance if I'm not "doing this right". I'm new to github.

I'm looking to use your version of attic as it incorporates a number of improvements over jborg's most recent release.

I do realise you haven't made any releases yet, but was wondering if you could advise if you know of any particular commit which passes the test suite?

I've tried that latest edition of the merge-all branch (commit d2c2b9) and although it builds and installs the test suite has multiple failures that appear quite serious.

Finally, I appreciate your efforts to improve on jborg's great work. 

Many thanks in advance.

**Comment by level323** [comment]
To partly answer my own question... I just tried running the test suite on jborg's own code and I got a bunch of errors also. I suspect something on my build machine is possibly broken and is causing this.

Can a dev advise if the test suites are currently in a fit state (supposed to pass)?

**Comment by ThomasWaldmann** [comment]
Best for me was to run the tests like:

```
fakeroot -u tox
```
It will then test all python seen in tox.ini (if you have them available).

**Comment by level323** [comment]
I did not know about tox until you mentioned it. Looks cool. I will use it to see if I can identify the cause(s) of the tests failing - will fire up a linux VM with various python versions and tox to test. In the meantime, I have a more urgent requirement to get a machine up and running, so was wondering if you could tell me the key build/test environment you're using (e.g. python version, distro)?

**Comment by ThomasWaldmann** [comment]
I use Ubuntu 14.04 64bit and misc. python 3.x versions to test.

**Comment by level323** [comment]
Can you categorically confirm that the test suite passes without error for you?
I ask because I've spent hours trying to get to the bottom of this issue and I've made basically zero forward progress. Here's what I've tried so far:
1. I created a VM from Debian 8 (Jessie) netinst ISO and installed attic from the debian repos (v0.13-1), ran the test suite and it **FAILED** (errors=10, skipped=4)
2. I created a VM from Debian 8 (Jessie) netinst ISO, installed all the attic deps from debian repos but the latest attic (jborg v0.14) via `pip3 install attic`, ran the test suite and it **FAILED**  (errors=10, skipped=4)
3. I created a VM from Debian 8 (Jessie) netinst ISO, installed only the non-python attic deps from from debian repos and the rest of the deps via pip3 and your version of the code (merge branch, commit 3d2a3d1) and the test suite also fails similarly.
4. Successfully installed your code (merge branch, commit 3d2a3d1) into a computer I have running a recently installed LXLE 14.04 system (based on Ubuntu 14.04). Successfully installed it to a venv but again the test suite fails similarly as described above. 

As you can see I've spent many hours trying to get to the heart of the test suite failures and have gotten precisely nowhere. 

Now that I've discovered that the test suite fails even for debian 8's packaged version of attic I'm seriously wondering where to go from here.

**Comment by level323** [comment]
Just a note that at this stage I'm working on the assumption that I'm doing something wrong or misunderstanding something about the testing process (I'm what I'd consider a dabbler in python, not a guru). So when I get more time I'll keep chugging away at getting to the bottom of it. In the meantime, thanks to @hubx for the reference to Travis.

**Comment by ThomasWaldmann** [comment]
All tests pass for me on my 64bit Ubuntu Linux and using fakeroot -u tox.
There's a harmless test failure on specific 32bit platform (raspberry pi, debian wheezy), but I'll fix that asap.

**Comment by level323** [comment]
Thanks very much for your kind offer to help. At this stage I'm assuming it's my own noobness that's at fault here, so I'll keep banging away at it here in my spare time and perhaps take you up on your kind offer sometime down the track if I'm still stuck.

**Comment by ThomasWaldmann** [comment]
not enough information to do anything further, closing.
