### ISSUE TITLE
Clarify install requirements regarding python-msgpack minimum version

### ISSUE THREAD

**Issue by level323** [attic/merge#3]
One of the issues I encountered when trying to work on #1 was that python-msgpack must be version 0.4.0 or greater. There seems to be a dependency in the code on the availability of the `use_bin_type` named argument when calling the packer. This argument was introduced, if I'm not mistaken, in version 0.4.0.

Suggest changing the docs to read something like "...Attic also requires msgpack-python **(>=0.4.0)** and sufficiently recent OpenSSL (>= 1.0.0)"

I accept that if built in a venv or pristine minimal python installation where attich is installed via pip will install a recent (therefore compatible) version of msgpack, but in my case (and perhaps others) in one case I was trying to build and install a recent commit of yours in an established (non-venv) python environment where the distro's (Ubuntu Trusty 14.04) version of python3-msgpack was installed and it was too old. Debian stable's version of msgpack is also too old.

**Comment by ThomasWaldmann** [comment]
The current setup.py here even requires 0.4.6 because of bugs and missing security features in older versions. You'll have troubles finding that in a linux distribution, too fresh.

**Comment by level323** [comment]
Perhaps a recommendation should be added to the docs that attic may need to be installed and built in a venv because key dependencies will likely be out of date in the 'real' python installation of current distros?

**Comment by ThomasWaldmann** [comment]
I updated the readme to point to setup.py install_requires for the requirements.
It doesn't matter how you provide them, so virtualenv is just one method.
